### ISSUE TITLE
Fixes #1

### ISSUE THREAD

**Issue by winterreise** [gbrl/mothertruckers#1]

**Comment by gbrl** [comment]
👍🏽

**Comment by heesooko** [comment]
👍🏼

On Wednesday, May 18, 2016, Gabriel Rambert notifications@github.com
wrote:

> 👍🏽
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gbrl/mothertruckers/issues/1#issuecomment-220222104

## 

The School of Arts and Sciences
University of Pennsylvania | Class of 2018
heesooko@sas.upenn.edu
Tel: (267) 252-7076
